<a href="https://colab.research.google.com/github/YamenObeidat/Activity-3--DBSCAN-PCA/blob/main/final_project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.manifold import TSNE
from sklearn.cluster import DBSCAN
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import silhouette_score, davies_bouldin_score, precision_score, recall_score, f1_score, roc_auc_score
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

%matplotlib inline
sns.set(style="whitegrid")

In [2]:
df = pd.read_csv('credit_card_fraud_10k.csv')
df.head()

,transaction_id,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,1,84.47,22,Electronics,0,0,66,3,40,0
1,2,541.82,3,Travel,1,0,87,1,64,0
2,3,237.01,17,Grocery,0,0,49,1,61,0
3,4,164.33,4,Grocery,0,1,72,3,34,0
4,5,30.53,15,Food,0,0,79,0,44,0

In [3]:
df_cleaned = df.drop(columns=['transaction_id'])

le = LabelEncoder()
df_cleaned['merchant_category'] = le.fit_transform(df_cleaned['merchant_category'])

df_cleaned.head()

,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age,is_fraud
0,84.47,22,1,0,0,66,3,40,0
1,541.82,3,4,1,0,87,1,64,0
2,237.01,17,3,0,0,49,1,61,0
3,164.33,4,3,0,1,72,3,34,0
4,30.53,15,2,0,0,79,0,44,0

In [4]:
X = df_cleaned.drop(columns=['is_fraud'])
y = df_cleaned['is_fraud']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_preprocessed = pd.DataFrame(X_scaled, columns=X.columns)
X_preprocessed.head()

,amount,transaction_hour,merchant_category,foreign_transaction,location_mismatch,device_trust_score,velocity_last_24h,cardholder_age
0,-0.521597,1.503345,-0.699651,-0.329244,-0.306158,0.195528,0.691873,-0.231580
1,2.086108,-1.241383,1.420290,3.037260,-0.306158,1.172909,-0.704299,1.370727
2,0.348151,0.781048,0.713643,-0.329244,-0.306158,-0.595686,-0.704299,1.170439
3,-0.066254,-1.096923,0.713643,-0.329244,3.266284,0.474779,0.691873,-0.632157
4,-0.829151,0.492130,0.006996,-0.329244,-0.306158,0.800573,-1.402386,0.035471